### ISSUE TITLE
`<=` breaks highlighting

### ISSUE THREAD

**Issue by seratch** [nishtahir/language-kotlin#15]
Having `<=` in if statements breaks highlighting.

```kotlin
if (num <= 10) {
  // foo
}
```

```kotlin
if (num <= 10) {
  errors["num"] = "Something is wrong"
}
```

Screen shot as of Oct 2019:
<img width="437" alt="Screen Shot 2019-10-25 at 15 14 22" src="https://user-images.githubusercontent.com/19658/67607661-25737c00-f73a-11e9-89f5-4d90a8fa5c16.png">

**Comment by paulstelian97** [comment]
Random hunch: does the order of definitions inside the language file matter? (< being matched in literal-function or on the contrary on the types: part)

**Comment by mmazurkevich** [comment]
GitHub uses this grammar to highlight all kotlin files [Linguist](https://github.com/github/linguist/blob/master/vendor/README.md). Example of broken highlighting https://git.io/Jfsdc. The root cause: `<` symbol parses as `punctuation.definition.generic.begin.kotlin` instead of keyword.operator.comparison.kotlin

**Comment by paulstelian97** [comment]
Isn't there a way to make the tokenizer also have a context which can allow this situation to be disambiguated?
