### ISSUE TITLE
Name of an object highlighted differently than a class name

### ISSUE THREAD

**Issue by starsep** [nishtahir/language-kotlin#27]
Not sure whether that's a bug but looks like one - name of an `object` is highlighted differently a `class` name.
It's probably due to different handling of `object`.
I think that's caused by `companion object` syntax/object expression, right?
Example:
```kotlin
  object ExampleObject
//^^^^^^ source.kotlin storage.type.kotlin
//       ^^^^^^^^^^^^^ source.kotlin entity.name.type.class.kotlin
  class ExampleClass
//^^^^^ source.kotlin meta.class.kotlin storage.modifier.kotlin
//      ^^^^^^^^^^^^ source.kotlin meta.class.kotlin entity.name.class.kotlin
```

**Comment by nishtahir** [comment]
Yeah, that doesn't seem right. `object` should be scoped the same as a class. I think it's because `object` is currently pulling the scope from Ident while `class` is getting it from its `class` definition. You're right that root cause of this is likely because I split `object` and class into two separate files. I ran into a few bugs on `object` that became difficult to address without breaking the scopes for `class`

**Comment by Animeshz** [comment]
Both of them seems very similar to me 🤔 Is it fixed?

**Comment by starsep** [comment]
> Both of them seems very similar to me 🤔 Is it fixed?

Indeed it is!
