### ISSUE TITLE
`import` not highlighted correctly when followed by items in <root>

### ISSUE THREAD

**Issue by ksqsf** [nishtahir/language-kotlin#52]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/23358293/113587419-56f7b300-9661-11eb-942e-7d1aceb2e949.png">

`knownSemantics` is a variable in `<root>`, and `Interpreter` and `Schema` are classes in `<root>`.

**Comment by Animeshz** [comment]
Related: 
![image](https://user-images.githubusercontent.com/26714676/118009678-e3397c00-b36b-11eb-87b8-09498655036c.png)
The last backtick is not recognized if backticks go around the dot (`.`).

https://github.com/nishtahir/language-kotlin/blob/5738095b675a42b520b40b673ba2ea52f50cd91c/src/imports.YAML-tmLanguage#L5
Original regex also breaks in some `as` usages as well as some syntax error (it may occupy whole file if no next backtick is found.
![image](https://user-images.githubusercontent.com/26714676/118011272-76bf7c80-b36d-11eb-80e6-f9d83f5a6cdd.png)

Why not a simpler regex (I was considering this easier one, because it doesn't break, and we're not verifying the syntax errors cuz we're not extracting AST maybe ¯\\_(ツ)_/¯)?
![image](https://user-images.githubusercontent.com/26714676/118011012-2e07c380-b36d-11eb-9020-b8c24257ad15.png)
